# Generated by Django 5.0.6 on 2024-05-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskPage', '0002_alter_tasks_options_tasks_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='createdBy',
            field=models.CharField(max_length=100),
        ),
    ]
