# Generated by Django 5.0.6 on 2024-05-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(choices=[(True, 'Completed'), (False, 'Uncompleted')]),
        ),
    ]
