# Generated by Django 5.0.6 on 2024-05-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPages', '0002_alter_user_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(),
        ),
    ]
