# Generated by Django 5.0.6 on 2024-05-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='tasks',
            name='createdBy',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.TextField(default='admin', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.BooleanField(choices=[(True, 'Completed'), (False, 'Uncompleted')], default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='taskID',
            field=models.IntegerField(default=0),
        ),
    ]
