# Generated by Django 5.0.6 on 2024-05-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskPage', '0004_rename_tasks_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['taskID']},
        ),
    ]
