# Generated by Django 5.0.6 on 2024-05-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskPage', '0005_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
